# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/cpuguy83/go-md2man
%global goipath         github.com/cpuguy83/go-md2man
Version:                2.0.3

%gometa

%global goaltipaths     github.com/cpuguy83/go-md2man/v2

%global common_description %{expand:
Converts markdown into roff (man pages).}

%global golicenses      LICENSE.md
%global godocs          README.md go-md2man.1.md

Name:           %{goname}
Release:        9%{?dist}
Summary:        Converts markdown into roff (man pages)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

Provides:       go-md2man = %{version}-%{release}
Provides:       golang(github.com/russross/blackfriday/v2) = 2

%description %{common_description}

%gopkg

%prep
%if %{defined rhel}
%goprep -k
# unpack vendored dependencies to GOPATH
tar c -C vendor/ . | tar x -C %{gobuilddir}/src
%else
%goprep

%generate_buildrequires
%go_generate_buildrequires
%endif

%build
%gobuild -o %{gobuilddir}/bin/go-md2man %{goipath}
%{gobuilddir}/bin/go-md2man -in go-md2man.1.md -out go-md2man.1

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -Dpm 0644 go-md2man.1 -t %{buildroot}%{_mandir}/man1/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md %{?rhel:vendor/modules.txt}
%doc go-md2man.1.md README.md
%{_bindir}/*
%{_mandir}/man1/go-md2man.1*

%gopkgfiles

%changelog
* Mon Apr 07 2025 Jindrich Novy <jnovy@redhat.com> - 2.0.3-9
- add Provides: golang(github.com/russross/blackfriday/v2)
- Resolves: RHEL-86199

* Thu Nov 07 2024 Jindrich Novy <jnovy@redhat.com> - 2.0.3-8
- re-add -devel and compat
- Resolves: RHEL-65351

* Wed Oct 30 2024 Jindrich Novy <jnovy@redhat.com> - 2.0.3-7
- don't build devel and compat packages
- Resolves: RHEL-65307
